# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-05-05 07:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('nodebb', '0004_auto_20190524_0700'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionCommunityMembership',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionCommunityThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodebb.DiscussionCommunity')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodebb.DiscussionCommunityMembership')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='discussioncommunitymembership',
            name='communities',
            field=models.ManyToManyField(through='nodebb.DiscussionCommunityThrough', to='nodebb.DiscussionCommunity'),
        ),
    ]
