# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-05-07 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodebb', '0005_auto_20200507_0414'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='discussioncommunitymembership',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='discussioncommunitymembership',
            name='community',
        ),
        migrations.RemoveField(
            model_name='discussioncommunitymembership',
            name='user',
        ),
        migrations.DeleteModel(
            name='DiscussionCommunityMembership',
        ),
    ]
