# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-05-07 10:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodebb', '0004_auto_20190524_0700'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussioncommunitymembership',
            old_name='community',
            new_name='community_url',
        ),
        migrations.AlterUniqueTogether(
            name='discussioncommunitymembership',
            unique_together=set([('user', 'community_url')]),
        ),
    ]
